import type { HomeContent } from "./types";

export const DEFAULT_HOME: HomeContent = {
  heroTitleTr: "Vize Sürecinizi Ranz Global ile Güvenle Yönetin",
  heroTitleEn: "Manage your visa process with Ranz Global",
  heroLeadTr:
    "Türkiye ve KKTC’den İngiltere, ABD, Kanada, Schengen ve diğer ülke vize başvurularınızda profesyonel danışmanlık.\n\nBaşvurunuzu değerlendiriyor, kişiye özel evrak listenizi hazırlıyor ve dosyanızı başvuruya hazır hale getiriyoruz.",
  heroLeadEn:
    "Professional consultancy for UK, US, Canada, Schengen and other visa applications from Türkiye and the TRNC.\n\nWe assess your case, prepare a document list for you, and get the file ready to apply.",
  ctaPrimaryTr: "Vize danışmanlığı al",
  ctaPrimaryEn: "Get visa consultancy",
  ctaSecondaryTr: "Mevcut müşteriyim — dosyama gir",
  ctaSecondaryEn: "I’m a client — open my file",
  destTitleTr: "Nereye gitmek istiyorsunuz?",
  destTitleEn: "Where do you want to go?",
  destNoteTr: "Ülkeyi seçin; ücret, kapsam ve başvuru adımı o sayfada açılır.",
  destNoteEn: "Choose a country; fee, scope and the start button open on that page.",
  destCards: [
    { id: "ingiltere", titleTr: "İngiltere", titleEn: "United Kingdom", hintTr: "Ziyaretçi", hintEn: "Visitor" },
    { id: "abd", titleTr: "ABD", titleEn: "USA", hintTr: "B1/B2", hintEn: "B1/B2" },
    { id: "kanada", titleTr: "Kanada", titleEn: "Canada", hintTr: "Ziyaretçi", hintEn: "Visitor" },
    { id: "schengen", titleTr: "Schengen", titleEn: "Schengen", hintTr: "Avrupa", hintEn: "Europe" },
    { id: "dubai", titleTr: "Dubai / BAE", titleEn: "Dubai / UAE", hintTr: "Turistik", hintEn: "Tourism" },
    { id: "cin", titleTr: "Çin", titleEn: "China", hintTr: "Turistik", hintEn: "Tourism" },
    { id: "rusya", titleTr: "Rusya", titleEn: "Russia", hintTr: "Davetiye", hintEn: "Invitation" },
  ],
  stepsTitleTr: "Üç adım. Fazlası yok.",
  stepsTitleEn: "Three steps. Nothing extra.",
  steps: [
    {
      id: "s1",
      n: "01",
      titleTr: "Ülkeyi seçin",
      titleEn: "Choose the country",
      bodyTr: "Schengen, ABD, BAE, Çin, Rusya, İngiltere veya Kanada. Evrak listesi o ülkeye göre açılır.",
      bodyEn: "Schengen, USA, UAE, China, Russia, UK or Canada. The checklist follows that country.",
    },
    {
      id: "s2",
      n: "02",
      titleTr: "Evrakları yükleyin",
      titleEn: "Upload documents",
      bodyTr: "Pasaport, rezervasyon, mali belgeler. Eksik olanlar net işaretlenir.",
      bodyEn: "Passport, bookings, finances. Missing items are clearly marked.",
    },
    {
      id: "s3",
      n: "03",
      titleTr: "Danışman inceler",
      titleEn: "Advisor reviews",
      bodyTr: "Onay, revizyon veya not. Durumu panelden ve bildirimle görürsünüz.",
      bodyEn: "Approve, revise or comment. You see status in the portal.",
    },
  ],
  visaEyebrowTr: "Ranz Global",
  visaEyebrowEn: "Ranz Global",
  visaTitleTr: "Vize danışmanlığı",
  visaTitleEn: "Visa consultancy",
  visaLeadTr:
    "Schengen, ABD, Birleşik Arap Emirlikleri, Çin, Rusya, İngiltere ve Kanada başvurularınızı tek yerden yönetin. Ülkeyi seçin; evrak listesi ona göre açılır.",
  visaLeadEn: "Manage Schengen, USA, UAE, China, Russia, UK and Canada files in one place. Choose the country; the document list follows it.",
  visaCards: [
    { id: "v1", titleTr: "Schengen", titleEn: "Schengen", hintTr: "Avrupa kısa konaklama evrakları", hintEn: "European short-stay documents" },
    { id: "v2", titleTr: "ABD", titleEn: "USA", hintTr: "DS-160 ve mali belgeler", hintEn: "DS-160 and financial evidence" },
    { id: "v3", titleTr: "BAE", titleEn: "UAE", hintTr: "Pasaport, otel ve iş belgesi", hintEn: "Passport, hotel and employment" },
    { id: "v4", titleTr: "Çin", titleEn: "China", hintTr: "Form, davet ve program", hintEn: "Form, invitation and itinerary" },
    { id: "v5", titleTr: "Rusya", titleEn: "Russia", hintTr: "Davetiye ve sigorta", hintEn: "Invitation and insurance" },
    { id: "v6", titleTr: "İngiltere & Kanada", titleEn: "UK & Canada", hintTr: "Banka, iş ve bağ belgesi", hintEn: "Bank, work and ties" },
  ],
  contactEyebrowTr: "İletişim",
  contactEyebrowEn: "Contact",
  contactTitleTr: "Bize yazın",
  contactTitleEn: "Get in touch",
  contactLeadTr: "Yalnızca ad soyad, telefon ve mesajınız. Danışmanımız sizi arar.",
  contactLeadEn: "Just your name, phone and message. An advisor will call you.",
  trustTitleTr:
    "Vize formlarını doldurma karmaşasından ve yanlış evrak derleme risklerinden arının. Ranz Global vize başvuru sürecinizin her adımında yanınızda.",
  trustTitleEn:
    "Leave behind the chaos of visa forms and the risk of compiling the wrong documents. Ranz Global is with you at every step of your application.",
  trustBodyTr:
    "Kayıt olup giriş yapın ve size belirtilen evrakları yükleyin. Alanında uzman danışmanlarımız evrakları kontrol etsin; kontrol sürecinin her adımını siz sadece takip edin.",
  trustBodyEn:
    "Register, sign in and upload the documents listed for you. Our specialist advisors review the file; you simply follow every step of the review.",
  galleryIds: [],
  email: "info@ranzglobal.com",
  phone: "+90 (212) 000 00 00",
  cityTr: "İstanbul, Türkiye",
  cityEn: "Istanbul, Turkey",
  footerNoteTr: "Ranz Global özel bir danışmanlık firmasıdır; konsolosluk veya devlet kurumu değildir.",
  footerNoteEn: "Ranz Global is a private consultancy, not a government or consular office.",
};
