import type { HomeContent } from "./types";
import { COMPANY, COMPANY_CITY_EN, COMPANY_CITY_TR } from "./company";

export const DEFAULT_HOME: HomeContent = {
  heroTitleTr: "Vize Sürecinizi Ranz Global ile Güvenle Yönetin",
  heroTitleEn: "Manage your visa process with Ranz Global",
  heroLeadTr:
    "Türkiye ve KKTC’den İngiltere, ABD, Kanada, Schengen ve diğer ülke vize başvurularınızda profesyonel danışmanlık.\n\nBaşvurunuzu değerlendiriyor, kişiye özel evrak listenizi hazırlıyor ve dosyanızı başvuruya hazır hale getiriyoruz.",
  heroLeadEn:
    "Professional consultancy for UK, US, Canada, Schengen and other visa applications from Türkiye and the TRNC.\n\nWe assess your case, prepare a document list for you, and get the file ready to apply.",
  ctaPrimaryTr: "Vize Başvurumu Başlat",
  ctaPrimaryEn: "Start My Visa Application",
  ctaSecondaryTr: "Müşteri Paneli",
  ctaSecondaryEn: "Client Portal",
  destTitleTr: "Nereye gitmek istiyorsunuz?",
  destTitleEn: "Where do you want to go?",
  destNoteTr: "Ülkeyi seçin; ücret, kapsam ve başvuru adımı o sayfada açılır.",
  destNoteEn: "Choose a country; fee, scope and the start button open on that page.",
  destCards: [
    { id: "ingiltere", titleTr: "İngiltere", titleEn: "United Kingdom", hintTr: "Ziyaretçi", hintEn: "Visitor" },
    { id: "abd", titleTr: "ABD", titleEn: "USA", hintTr: "B1/B2", hintEn: "B1/B2" },
    { id: "kanada", titleTr: "Kanada", titleEn: "Canada", hintTr: "Ziyaretçi", hintEn: "Visitor" },
    { id: "schengen", titleTr: "Schengen", titleEn: "Schengen", hintTr: "Avrupa", hintEn: "Europe" },
    { id: "asya", titleTr: "Asya", titleEn: "Asia", hintTr: "Vize gereken ülkeler", hintEn: "Visa-required countries" },
    { id: "afrika", titleTr: "Afrika", titleEn: "Africa", hintTr: "Vize gereken ülkeler", hintEn: "Visa-required countries" },
    { id: "dubai", titleTr: "Dubai / BAE", titleEn: "Dubai / UAE", hintTr: "Turistik", hintEn: "Tourism" },
    { id: "cin", titleTr: "Çin", titleEn: "China", hintTr: "Turistik", hintEn: "Tourism" },
    { id: "rusya", titleTr: "Rusya", titleEn: "Russia", hintTr: "Davetiye", hintEn: "Invitation" },
  ],
  stepsTitleTr: "Nasıl Çalışıyoruz?",
  stepsTitleEn: "How Do We Work?",
  steps: [
    {
      id: "s1",
      n: "01",
      titleTr: "Ülkeyi seçin",
      titleEn: "Choose the country",
      bodyTr: "Schengen, Asya, Afrika, ABD, BAE, Çin, Rusya, İngiltere veya Kanada. Evrak listesi o ülkeye göre açılır.",
      bodyEn: "Schengen, Asia, Africa, USA, UAE, China, Russia, UK or Canada. The checklist follows that country.",
    },
    {
      id: "s2",
      n: "02",
      titleTr: "Evrakları yükleyin",
      titleEn: "Upload documents",
      bodyTr: "Pasaport, rezervasyon, mali belgeler. Eksik olanlar net işaretlenir.",
      bodyEn: "Passport, bookings, finances. Missing items are clearly marked.",
    },
    {
      id: "s3",
      n: "03",
      titleTr: "Danışman inceler",
      titleEn: "Advisor reviews",
      bodyTr: "Onay, revizyon veya not. Durumu panelden ve bildirimle görürsünüz.",
      bodyEn: "Approve, revise or comment. You see status in the portal.",
    },
  ],
  visaEyebrowTr: "Ranz Global",
  visaEyebrowEn: "Ranz Global",
  visaTitleTr: "Vize danışmanlığı",
  visaTitleEn: "Visa consultancy",
  visaLeadTr:
    "Schengen, Asya, Afrika, ABD, Birleşik Arap Emirlikleri, Çin, Rusya, İngiltere ve Kanada başvurularınızı tek yerden yönetin. Ülkeyi seçin; evrak listesi ona göre açılır.",
  visaLeadEn: "Manage Schengen, Asia, Africa, USA, UAE, China, Russia, UK and Canada files in one place. Choose the country; the document list follows it.",
  visaCards: [
    { id: "v1", titleTr: "Schengen", titleEn: "Schengen", hintTr: "Avrupa kısa konaklama evrakları", hintEn: "European short-stay documents" },
    { id: "v7", titleTr: "Asya", titleEn: "Asia", hintTr: "Vize gereken Asya ülkeleri", hintEn: "Visa-required Asian countries" },
    { id: "v8", titleTr: "Afrika", titleEn: "Africa", hintTr: "Vize gereken Afrika ülkeleri", hintEn: "Visa-required African countries" },
    { id: "v2", titleTr: "ABD", titleEn: "USA", hintTr: "DS-160 ve mali belgeler", hintEn: "DS-160 and financial evidence" },
    { id: "v3", titleTr: "BAE", titleEn: "UAE", hintTr: "Pasaport, otel ve iş belgesi", hintEn: "Passport, hotel and employment" },
    { id: "v4", titleTr: "Çin", titleEn: "China", hintTr: "Form, davet ve program", hintEn: "Form, invitation and itinerary" },
    { id: "v5", titleTr: "Rusya", titleEn: "Russia", hintTr: "Davetiye ve sigorta", hintEn: "Invitation and insurance" },
    { id: "v6", titleTr: "İngiltere & Kanada", titleEn: "UK & Canada", hintTr: "Banka, iş ve bağ belgesi", hintEn: "Bank, work and ties" },
  ],
  contactEyebrowTr: "İletişim",
  contactEyebrowEn: "Contact",
  contactTitleTr: "Bize yazın",
  contactTitleEn: "Get in touch",
  contactLeadTr: "Yalnızca ad soyad, telefon ve mesajınız. Danışmanımız sizi arar.",
  contactLeadEn: "Just your name, phone and message. An advisor will call you.",
  trustTitleTr:
    "Vize formlarını doldurma karmaşasından ve yanlış evrak derleme risklerinden arının. Ranz Global vize başvuru sürecinizin her adımında yanınızda.",
  trustTitleEn:
    "Leave behind the chaos of visa forms and the risk of compiling the wrong documents. Ranz Global is with you at every step of your application.",
  trustBodyTr:
    "Kayıt olup giriş yapın ve size belirtilen evrakları yükleyin. Alanında uzman danışmanlarımız evrakları kontrol etsin; kontrol sürecinin her adımını siz sadece takip edin.",
  trustBodyEn:
    "Register, sign in and upload the documents listed for you. Our specialist advisors review the file; you simply follow every step of the review.",
  reviews: [
    {
      id: "lefkosa-1",
      bodyTr: "Dosyam ne oldu diye sürekli yazmıyorum artık. Danışmanın notu zaten ekranda duruyor.",
      bodyEn: "I don’t keep messaging to ask where my file is. The advisor’s note is already on the screen.",
      whoTr: "Lefkoşa",
      whoEn: "Nicosia",
    },
    {
      id: "girne-1",
      bodyTr: "Evrakları evden yükledim. Liste de, düzeltme de oradan geldi; ofise uğramadım.",
      bodyEn: "I uploaded the papers from home. The list and the corrections came there too; I didn’t go to an office.",
      whoTr: "Girne",
      whoEn: "Kyrenia",
    },
    {
      id: "magusa-1",
      bodyTr: "Schengen’de ne eksikse yanında yazıyordu. Hangisini göndereceğimi sormama gerek kalmadı.",
      bodyEn: "Whatever was missing for Schengen was written next to it. I didn’t have to ask what to send next.",
      whoTr: "Gazimağusa",
      whoEn: "Famagusta",
    },
    {
      id: "lefkosa-2",
      bodyTr: "İngiltere listesi bana göre gelmiş. Sponsor kısmını ayrı tutmuşlar, ben karıştırırdım.",
      bodyEn: "The UK list was made for my situation. They kept the sponsor part separate, which I would have mixed up.",
      whoTr: "Lefkoşa",
      whoEn: "Nicosia",
    },
    {
      id: "guzelyurt",
      bodyTr: "WhatsApp’tan pdf kayboluyordu. Burada yüklediğim yerde duruyor, aramıyorum.",
      bodyEn: "PDFs used to disappear on WhatsApp. Here they stay where I uploaded them, so I’m not hunting for files.",
      whoTr: "Güzelyurt",
      whoEn: "Morphou",
    },
    {
      id: "iskele",
      bodyTr: "Nereye başvuracağımı ilk günden söylediler. Pasaportuma bakıp kestirmeden konuştular.",
      bodyEn: "They told me on day one where I would file. They looked at my passport and didn’t leave it vague.",
      whoTr: "İskele",
      whoEn: "Trikomo",
    },
    {
      id: "lefke",
      bodyTr: "Banka dökümünde bir ay yokmuş. Onu yazdılar, ben de tamamladım. Başka bir şey uydurmadılar.",
      bodyEn: "One month was missing from the bank statements. They wrote that, I filled it in. They didn’t invent extra tasks.",
      whoTr: "Lefke",
      whoEn: "Lefka",
    },
    {
      id: "girne-2",
      bodyTr: "İlk telefonda anlaşıldı: ödediğim danışmanlık ücreti. Konsolosluk ayrı, onu da söylediler.",
      bodyEn: "It was clear on the first call: what I pay is consultancy. Consulate fees are extra, and they said so.",
      whoTr: "Girne",
      whoEn: "Kyrenia",
    },
    {
      id: "istanbul",
      bodyTr: "Herkese aynı listeyi atmamışlar. Benim evraklar ayrı duruyordu, eksik olanlar da belliydi.",
      bodyEn: "They didn’t send the same list to everyone. Mine was separate, and the gaps were obvious.",
      whoTr: "İstanbul",
      whoEn: "Istanbul",
    },
    {
      id: "izmir",
      bodyTr: "ABD’de formla evrakın aynı şeyi anlatması lazımmış. Onu uyardılar, iyi oldu.",
      bodyEn: "For the US, the form and the papers have to say the same thing. They flagged that, which helped.",
      whoTr: "İzmir",
      whoEn: "Izmir",
    },
    {
      id: "antalya",
      bodyTr: "Sigorta mı otel mi önce, karıştırmıştım. Listede sırası vardı, ona baktım.",
      bodyEn: "I had mixed up whether insurance or the hotel came first. The list had an order, so I followed that.",
      whoTr: "Antalya",
      whoEn: "Antalya",
    },
    {
      id: "ankara",
      bodyTr: "Kanada listesini panelden gördüm. Vizeyi alırsınız demediler, adımları gösterdiler.",
      bodyEn: "I saw the Canada list in the portal. They didn’t say I’d get the visa; they showed the steps.",
      whoTr: "Ankara",
      whoEn: "Ankara",
    },
  ],
  galleryIds: [],
  email: COMPANY.email,
  phone: "+90 530 925 88 92",
  cityTr: COMPANY_CITY_TR,
  cityEn: COMPANY_CITY_EN,
  footerNoteTr:
    `${COMPANY.brandNoteTr} ${COMPANY.legalName}; konsolosluklar ve resmi vize başvuru merkezlerinden bağımsız özel bir danışmanlık şirketidir. Nihai vize kararı ilgili ülkenin yetkili makamlarına aittir. Ranz Global vize onayı garantisi vermez.`,
  footerNoteEn:
    `${COMPANY.brandNoteEn} ${COMPANY.legalName} is a private consultancy, independent of consulates and official visa application centres. The final visa decision belongs to the competent authorities. Ranz Global does not guarantee visa approval.`,
};
